# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 01:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='user',
            new_name='post',
        ),
        migrations.AlterUniqueTogether(
            name='comentarios',
            unique_together=set([('post', 'comentario')]),
        ),
    ]
