# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_auto_20171122_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='egreso',
            field=models.DateField(),
        ),
    ]
